name: Java Build

on: [push]

jobs:
  Build-Artifacts:
    runs-on: linux-amd64
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Clone Repository
      run: |
        repo="ssh://git@git.mclarkdev.com:2222/${{ gitea.repository }}"
        echo "Cloning $repo" && git clone --recurse-submodules $repo .
        echo "Checking out $GITHUB_REF_NAME"; git checkout $GITHUB_REF_NAME
    - name: Set version number
      run: |
        echo -n "${{ github.run_id }}" > src/main/resources/app.version
    - name: Build artifacts with Maven
      run: mvn clean install
    - name: Package the server
      run: |
        mkdir server/
        cp -rv config server/
        cp -rv resources server/
        cp target/server.jar server/                     
    - name: Archive job artifact
      uses: actions/upload-artifact@v3
      with:
        name: server-${{ github.run_id }}
        path: |
          server/
